/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_JNITest */

#ifndef _Included_com_example_jnitest_JNITest
#define _Included_com_example_jnitest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_JNITest
 * Method:    JNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_JNITest_JNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_JNITest
 * Method:    Library
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitest_JNITest_Library
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_jnitest_JNITest
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_JNITest_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
